name: "Build"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
    - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install tarball+https://install.devenv.sh/latest

    - name: Build the devenv shell and run any pre-commit hooks
      run: devenv ci

    - name: Run a single command in the devenv shell
      run: devenv shell cargo test
